cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/tercume/adem/meal_tashih
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/zdepo
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/win_android/win_enc_ebook_realme/arac/updfs
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/win_android/pure_book_realme/arac/updfs
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/win_android/win_ebook_realme/arac/updfs
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/textFromAPKBook
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/denemeler/secmeler/v3logogen/dist
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/denemeler/secmeler/logogen/dist
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/android_projeler/arac_imgs
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/android_projeler/win_enc_ebook_realme/arac/updfs
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/android_projeler/win_ebook_realme/arac/updfs
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/android_projeler/enc_books_realme/arac/updfs
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/station_ebookReaderLinWin/arac/updfs
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/v2_ebookReaderLinWin/arac/updfs
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/v3_ebookReaderLinWin/arac/updfs
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java/ebookReaderLinWin/arac/updfs
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/java
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/x
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/irsal/eAlina
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/irsal
cp -fv bin/notdefteri_190426.jar /home/muratsivas76/istasyon/evrak
